name: mmRandoms
main: com.mmiillkkaa.randoms.RandomsPlugin
author: mmiillkkaa
load: STARTUP
version: '${project.version}'
commands:
  randomssetup:
    usage: /randomssetup
    description: Setup the plugin