name: mmRandoms
main: com.mmiillkkaa.randoms.RandomsPlugin
author: mmiillkkaa
version: '${project.version}'
commands:
  triggerrandom:
    usage: /triggerrandom [number]
    description: Triggers a random event for debugging purposes.
  randomssetup:
    usage: /randomssetup
    description: Setup the plugin